@startuml
title ai分析任务进程协程化(是否需要消息队列方式待定)

:执行分析脚本;
repeat
    :获取所有需要分析的数据;
    if (分析数据为空) then (是)
        :睡眠30秒;
    else (否)
        while (遍历处理单条需要分析的数据) is (存在数据)
            :对分析数据进行封装;
            :协程化:调用ai接口进行数据分析;
            :等待ai接口响应（非阻塞）;
            :存储ai接口相应到数据库，并变更分析数据状态;
        endwhile (不存在数据)
    endif
repeat while
@enduml
