@startuml
start
:1.0;
note left
时间：2011-01-24
功能上线：
    1.快速聊天功能
    2.个人头像设置
    3.不透露消息是否已读
    4.支持发送图片
end note

:1.1;
note right
时间：2011-03-28
功能上线：
    1.支持多人会话
    2.支持微博私信互通
    3.增加通讯录分组
    4.支持会话列表搜索
end note

:1.2;
note left
时间：2011-04-18
功能上线：
    1.支持通过验证工作邮箱，自动找到验证过相同工作邮箱的同事
    2.发消息支持插入表情
    3.支持添加好友备注
    4.添加黑名单，防止不必要的骚扰
end note

:2.0;
note right
时间：2011-05-18
功能上线：
    1.支持对讲功能，支持单人/1.支持多人对讲
    2.qq邮箱提醒
end note

:2.1;
note left
时间：2011-07-01
功能上线：
    1.寻找通讯录好友
    2.好友验证
    3.好友推荐消息
    4.隐私设置：可设置“允许通过qq号找到我”、“推送我给qq好友”
end note

:2.3;
note right
时间：2011-08-15
功能上线：
    1.查看附近人
    2.页面升级
    3.qq离线消息同步通知微信
    4.个性签名
    5.手机号注册微信
    6.微博私信，统一管理私信消息
    7.听筒切换
    8.绑定qq号
end note

:2.4;
note left
时间：2011-08-28
功能上线：
    1.通讯录安全助手，支持把手机通讯录安全备份到云端
end note

:3.0;
note right
时间：2011-10-18
功能上线：
    1.摇一摇
    2.漂流瓶，支持扔漂流瓶匿名交友
    3.视频信息
    4.支持繁体中文语音界面，增加港、澳、台、美、日五个地区的用户绑定手机号
    5.增加保存群组到通讯录功能
    6.系统插件可装卸、安装
    7.支持查看好友大头像
    8.添加免打扰插件
end note

:3.0.1;
note left
时间：2011-10-25
功能上线：
    1.修正了部分iphone手机不正常退出问题
end note

:3.1;
note right
时间：2011-11-17
功能上线：
    1.支持英文界面显示
    2.语音记事本支持同步内容QQ邮箱记事本
    3.文字、语音切换体验调整
    4.支持语音播放时 听筒模式/外放模式
end note

:3.5;
note left
时间：2011-12-14
功能上线：
    1.分离专属于自己的二维码到微博上，收获粉丝给你发来的招呼
    2.支持透明背景的动画表情、Emoji表情、自定义表情
    3.简化注册流程，支持全球超过100个国家和地区
    4.对话中可以进行石头剪刀布和扔骰子游戏
    5.对话页面支持自定义聊天背景
end note

:3.5.1;
note right
时间：2011-12-31
功能上线：
    1.摇一摇增加显示历史摇到的人
    2.部分体验优化，聊天背景增加纯色背景，体验更流畅
    3.修改了一些bug，使用更流畅，收发消息更及时
end note

:3.6;
note left
时间：2012-01-19
功能上线：
    1.群发助手，可以把通知、祝福等消息分别发送给各个好友
    2.取消语音，语音可以重来，祝福更完美
    3.微博精选，腾讯新闻带给你不一样的阅读体验
    4.祝福有惊喜，彩蛋一触即发
    5.支持写邮箱，添加附件发邮箱
end note

:4.0;
note right
时间：2012-05-24
功能上线：
    1.你可以拥有一个精美的相册，将生活记录在相册中
    2.支持把照片分享到朋友圈，让所有微信通讯录里的朋友看到，他们还可以对照片评论和赞
    3.微信开放接口，支持从第三方应用向微信通讯录里的朋友分享音乐、新闻、摄像等消息内容
    4.支持图片、视频转发给其他微信朋友
    5.可以对某个通讯录里的朋友坐标，这样就可以快速在通讯录顶部的星标分组里找到他们了
    6.支持对多个微信好友群发消息，减少你重复繁琐的操作工作
end note

:4.2;
note left
时间：2012-08-21
功能上线：
    1.新增视频聊天插件，是时候和朋友面对面了
    2.新增微信网页版，便捷的二维码扫描入口，让你快速进入微信生活
    3.朋友圈新增评论回复功能，发图还能选择可见范围
    4.全新的微信名片设计，让你更具魅力
end note

:4.3;
note right
时间：2012-11-01
功能上线：
    1.新增摇一摇传图，你可以将电脑网页的图片传到手机上，更可以让好友也摇到你的图片
    2.你可以通过语音搜索，从通讯录中查找朋友
    3.微信号可以解绑QQ号和手机号码
    4.动画表情可以从网上下载
    5.”扫一扫“可以扫描任何二维码，甚至能识别二维码电子名片，并导入手机通讯录
    6.新增聊天置顶，可把有待办事项的聊天置顶，方便稍后处理
    7.你可以在聊天中滑动查看图片
    8.你可以不查看某人的朋友圈更新，并可以把朋友圈上的私密照片公开
end note

:4.3.2;
note left
时间：2013-01-04
功能上线：
    1.解决朋友圈发图模糊的问题
    2.调整朋友圈权限，保护账号隐私
end note

:4.5;
note right
时间：2013-02-06
功能上线：
    1.实时对讲，多人实时语音聊天
    2.将正在听的歌曲摇到手机里
    3.群聊支持二维码，扫一扫就能加入
    4.聊天记录可以迁移到另外的手机上
    5.语音可以撤销发送
    6.推荐一个有趣的公众号：“语音提醒”
    7.回复陌生人的打招呼，还能加备注
    8.朋友发来的位置可以导航
end note

:5.0;
note left
时间：2013-08-09
功能上线：
    1.表情商城，有趣好玩的表情
    2."扫一扫"，可以扫条形码、图书和CD封面、街景，还可以翻译英文单词
    3.可以在游戏中心，和朋友们一起玩游戏
    4.绑定银行卡，在公众号、扫二维码、APP中实现一键支付
    5.新增收藏功能，可以收藏聊天、公众号、朋友圈的信息
    6.新增添加朋友方式：”按住添加朋友“
    7.自主研发的语音识别技术，可直接在聊天中语音输入
    8.订阅号的消息被折叠起来，让你的消息列表更干净
    9.左划可以删除聊天记录，双击左下角”微信“可以定位到最新一条未读消息
    10.双击文字消息，可查看全文
end note

:5.0.2;
note right
时间：2013-09-16
功能上线：
    1.可以在”我“的页面绑定银行卡
    2.修复一个系统安全漏洞导致的问题
    3.修复部分手机无法听语音的问题
    4.其它bug修复
end note

:5.0.3;
note left
时间：2013-11-01
功能上线：
    1.可以转发多条聊天记录，或者通过邮件备份
    2.可以从地点列表中选择一家餐馆或商店，精确发送地理位置
    3.可以在聊天中选择收藏的内容发送，收藏的文字可编辑
    4.清理微信存储空间：删除不再需要的文件，减少微信占用的存储空间
end note

:5.1;
note right
时间：2013-12-23
功能上线：
    1.可将有需要的群，人数上线提升为100人
    2.飞机大战游戏
    3.话费充值时会自动检查，防止输入陌生号码
    4.在表情包购买界面，长按表情可预览
    5.未发出的消息草稿，会显示在聊天列表中
end note

:5.2;
note left
时间：2014-01-26
功能上线：
    1.可以在聊天中查看大家的实时位置，还能一起对讲
    2.”我的银行卡“中增加多项生活服务
    3.聊天记录也支持搜索
    4.长按语音消息，可以转换为文字
    5.新增”图片墙“，帮你快速回顾聊天中的图片
    6.发消息时，会为你推荐已下载的表情，还可以把你喜欢的表情分享给朋友和朋友圈
    7.在群聊中被人@到，会收到提醒
    8.可以给你的朋友添加更多文字描述和图片备注
end note

:5.2.1;
note right
时间：2014-03-24
功能上线：
    1.发朋友圈时，可以附上你所在的餐馆或景点
    2.可以通过腾讯电脑管家将微信聊天记录备份到电脑上
end note

:5.3;
note left
时间：2014-05-26
功能上线：
    1.聚会见面，大家输入相同数字可加入同一个群
    2.给你的收藏添加标签，可分类查看
    3.可将多条聊天消息收藏在一起
    4.长按外文消息，可翻译成你的语言
    5.发朋友圈时可以创建新的位置信息
end note

:5.3.1;
note right
时间：2014-06-27
功能上线：
    1.给朋友添加标签，方便分类和查找
    2.管理”我的钱包“中的零钱，直接支付
    3.在”我的钱包“中可以向你的朋友转账
    4.可以撤回2分钟内发出的最后一条消息
end note

:5.4;
note left
时间：2014-08-28
功能上线：
    1.现在除了搜索联系人和聊天记录，还可以搜索公众号、公众号文章、收藏、微信功能
    2.查看图片时，可以识别图中的二维码
    3.面都面收钱：通过二维码给身边的人转账
end note

@enduml
