@startuml

start
:1.0;
note right
时间：2011-01-24
功能上线：
    1.快速聊天功能
    2.个人头像设置
    3.不透露消息是否已读
    4.支持发送图片
功能下架：
    无
end note

:1.1;
note right
时间：2011-03-28
功能上线：
    1.支持多人会话
    2.支持微博私信互通
    3.增加通讯录分组
    4.支持会话列表搜索
功能下架：
    无
end note

:1.2;
note right
时间：2011-05-18
功能上线：
    1.支持通过验证工作邮箱，自动找到验证过相同工作邮箱的同事
    2.发消息支持插入表情
    3.支持添加好友备注
    4.添加黑名单，防止不必要的骚扰
功能下架：
    无
end note

:2.0;
note right
时间：2011-05-18
功能上线：
    1.支持对讲功能，支持单人/1.支持多人对讲
    2.qq邮箱提醒
功能下架：
    无
end note

:2.1;
note right
时间：2011-07-11
功能上线：
    1.寻找通讯录好友
    2.好友验证
    3.好友推荐消息
    4.隐私设置：可设置“允许通过qq号找到我”、“推送我给qq好友”
功能下架：
    无
end note

:2.3;
note right
时间：2011-08-15
功能上线：
    1.查看附近人
    2.页面升级
    3.qq离线消息同步通知微信
    4.个性签名
    5.手机号注册微信
    6.微博私信，统一管理私信消息
    7.听筒切换
    8.绑定qq号
功能下架：
    无
end note

:2.4;
note right
时间：2011-08-28
功能上线：
    1.通讯录安全助手，支持把手机通讯录安全备份到云端
功能下架：
    无
end note

:3.0;
note right
时间：2011-10-18
功能上线：
    1.摇一摇
    2.漂流瓶，支持扔漂流瓶匿名交友
    3.视频信息
    4.支持多语言版本（港、澳、台、美、日）
    5.增加保存群组到通讯录功能
    6.系统插件可装卸、安装
    7.支持查看好友大头像
    8.添加免打扰插件
功能下架：
    无
end note

:3.0.1;
note right
时间：2011-10-25
功能上线：
    1.修复bug，提高稳定性
    2.解决部分机型无法录制视频的问题
    3.优化性能，提高运行速度
功能下架：
    无
end note
@enduml
