@startmindmap
+ 总结
++ 两条关键原则
+++ 编写清晰具体的指令
+++ 如果适当的话，给模型一些思考时间

+ 提示词原则
++ 编写清晰、具体的指令
+++ 使用分解符清晰地表示输入的不同部分
+++ 要求一个结构化的输出
+++ 要求模型检查是否满足条件
+++ 提供少量示例
++ 给模型时间去思考
+++ 指定完成任务所需的步骤
+++ 指导模型在下结论之前找出一个自己的解法
++ 局限性
+++ 虚假知识

+ 迭代优化
++ 任务：从产品说明书生成一份营销产品描述
+++ 生成文本太长
+++ 文本关注在错误的细节上
+++ 需要一个表格形式的描述

+ 文本概括
++ 单一文本概述Prompt实验
+++ 限制输出文本长度
+++ 关键角度侧重
+++ 关键信息提取
++ 多条文本概括Prompt实验

+ 文本推断
++ 尚品评论
+++ 情感（正向、负向）
+++ 识别情感类型
+++ 识别愤怒
+++ 从客户评论中提取产品和公司名称
++ 推断主题
+++ 判断5个主题
+++ 为特定主题制作新闻提醒

+ 文本转换
++ 文本翻译
+++ 中文转西班牙语
+++ 识别语种
+++ 多语种翻译
+++ 翻译+正式语气
+++ 通用翻译器
++ 语气/风格调整
++ 格式转换
++ 拼写及语法纠正

+ 文本扩展

+ 聊天机器人
@endmindmap