@startmindmap
* 阿斯顿
+ PHP知识点
++ 架构知识
+++ php-fpm

++ 运用知识
+++ json_encode解析大json字符串
++++ 解析耗时： <100kb 约 0.1-1.5ms,1mb 约 5-10ms,5mb 约 50-80ms
++++ 核心原因是：内存拷贝 + 单线程递归解析 + 无流式处理
++++ 1.内存拷贝：php中字符串是不可变类型，所以要多次copy
++++ 2.解析算法：递归解析 + 无并行优化
++++ 3.无流式解析：必须全量加载

-- PHP基础
--- 数据类型
---- 可变类型(array、object、resource、callable):创建后，修改时，直接改旧内存地址的值
---- 不可变类型(string、int、float、bool、null):创建后，就无法修改，任何修改操作都会生成一个新值

@endmindmap