@startmindmap
+ php-fpm项目内存的占比
++ 千色
+++ 碧乐淘、乐享荟
++++ 单个进程大概占用内存:16M
++++ 1G内存大概能开启进程数（占用80%）:65(50)
++++ 单个进程大概相应时间:100ms
++ 保伦
+++ 教育云平台
++++ 单个进程大概占用内存:20M
++++ 1G内存大概能开启进程数（占用80%）:50(40)
++++ 单个进程大概相应时间:100ms


+ 框架内存占比
++ php-fpm
++ swoole
@endmindmap